snake:
	qemu-system-i386 -drive file=snake.img,format=raw -monitor stdio

dxball:
	qemu-system-i386 -drive file=dxball.img,format=raw -monitor stdio

space:
	qemu-system-i386 -drive file=space.img,format=raw -monitor stdio
